language: bash
services: docker

before_script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - cd docker && ./makeDockerfiles.sh

after_script:
  - docker images
